In [1]:
import numpy as np # numerical python, np - alias

In [4]:
x = [2, 5, 5]
y = [9, 4, 2]
print(x+y)
x_np = np.array(x)
y_np = np.array(y)
print(type(x_np)) # nd - n-dimensional
print(x_np)

[2, 5, 5, 9, 4, 2]
<class 'numpy.ndarray'>
[2 5 5]


In [8]:
print(x_np + y_np)
print(x_np * y_np)
print((x_np + y_np)/2)
print(np.log(x_np))

[11  9  7]
[18 20 10]
[5.5 4.5 3.5]
[0.69314718 1.60943791 1.60943791]


In [9]:
np.array([0.62, 0.72]) * 100

array([62., 72.])

In [11]:
A = [[3, 5, 1], [5, 10 ,4], [4, 20, 4]]
A[1][0]

5

In [12]:
A_np = np.array(A)
print(A_np)

[[ 3  5  1]
 [ 5 10  4]
 [ 4 20  4]]


In [19]:
print(A_np[0][1])
print(A_np[0, 1]) # этот способ быстрее
print(A_np[1])
print(A_np[:, 2]) # достаем колонку
print(A_np[:2, 2]) # достаем первые два элемента третьей колонки

5
5
[ 5 10  4]
[1 4 4]
[1 4]


In [26]:
example = ['cat', 2, True, 4.2]
print(example)
example_np = np.array(example)
print(example_np) # пакет не смог все преобразовать в цифры, поэтому он взял и сделал
# гомогенным весь массив данных, то есть сделал все строками
# короче эта штука хранит массивы только в одном типе данных

['cat', 2, True, 4.2]
['cat' '2' 'True' '4.2']


In [27]:
example = [2, True, 4.2] # превращает все элементы в float
example

[2, True, 4.2]

In [32]:
print(x_np.std())
print(x_np.mean())

1.4142135623730951
4.0


In [86]:
A_np

array([[ 3,  5,  1],
       [ 5, 10,  4],
       [ 4, 20,  4]])

In [65]:
print(A_np.mean())
print(A_np[:, 1].mean())
print(A_np.mean(axis = 0)) # среднее по колонкам
print(A_np.mean(axis = 1)) # среднее по рядам

6.222222222222222
11.666666666666666
[ 4.         11.66666667  3.        ]
[3.         6.33333333 9.33333333]


In [40]:
np.median(x_np)

5.0

In [50]:
A_np.size

9

In [51]:
ages = np.array([[15, 23, 32, 45, 52], 
               [68, 34, 55, 78, 20], 
               [25, 67, 33, 45, 14]])

In [52]:
ages

array([[15, 23, 32, 45, 52],
       [68, 34, 55, 78, 20],
       [25, 67, 33, 45, 14]])

In [56]:
~((ages >= 18) & (ages <= 65)) # and, not = ~

array([[ True, False, False, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [55]:
(ages < 18) | (ages > 65) # or

array([[ True, False, False, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [57]:
ages[(ages < 18) | (ages > 65)] # boolean mask

array([15, 68, 78, 67, 14])

In [59]:
x_np[[True, True, False]]

array([2, 5])

In [60]:
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

In [79]:
# Посчитать, сколько слушателей получили 0 за вступительный экзамен.
len(scores[(scores == 0)])
(scores == 0).sum()

13

In [63]:
# Посчитать, сколько слушателей получили балл выше 50.
len(scores[(scores > 50)])

64

In [64]:
# Посчитать, сколько человек получили балл не ниже 50, но не выше 70.
len(scores[(scores >= 50) & (scores <= 70)])

26

In [81]:
# Определить, в какой группе средний балл за вступительный экзамен выше.
scores.mean(axis = 1).argmax() # находим индекс максимального элемента

9

In [75]:
# Используя массив nonzero, определить минимальный вступительный балл по всем группам.
nonzero = scores[(scores > 0)]
nonzero.min()

1

In [77]:
# Выбрать из массива nonzero только те значения, которые соответствуют продвинутому 
# уровню знания языка – баллу за экзамен выше 80. Сохранить полученный результат в 
# массив advanced.

advanced = nonzero[(nonzero > 80)]
advanced

array([ 98, 100,  82, 100, 100,  95,  83, 100,  94,  90,  87,  89,  99,
        88,  94, 100,  81,  98,  88, 100,  86,  96, 100,  98,  87, 100,
        88,  89])

In [82]:
# Определить размерность массива advanced
len(advanced)

28